name: Release
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install deps
        run:
          pnpm i --frozen-lockfile

      - name: Build
        run: |
          pnpm build

      - name: Set version to release tag
        shell: bash
        run: pnpm version from-git --no-commit-hooks --no-git-tag-version --allow-same-version

      - name: Publish
        shell: bash
        run: |
           cp package.json dist/package.json
           pnpm publish dist --access public --no-git-checks

      - name: Push version changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json
