name: CD
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Install deps
        run:
          pnpm i --frozen-lockfile

      - name: Build and publish
        run: |
          pnpm build
          cp package.json dist/package.json
          cp src/index.d.ts dist/index.d.ts  
          pnpm publish dist --access public