name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Install deps
        run:
          pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm tsc --noEmit

      - name: Test
        run: pnpm test
